### ISSUE TITLE
MTD

### ISSUE THREAD

**Issue by vdrtuxnet** [jasmin-j/vdr-plugin-ddci2#1]
Hello Jasmin,

thank you for the plugin!

Do you have any plans to integrate the MTD feature
in the near future?

Best rgards

**Comment by jasmin-j** [comment]
Hello vdrtuxnet!

I had in the past, but now I have so much other things to do. You know, lack of time, other
interesting things, more company work.

The problem is, that I need to research about the PIDs and other stuff, how to make
them unique across different TV stations. Moreover, how this is handled internally
by VDR and what I can reuse. I guess there would be a lot to reuse with only little changes
in VDR. But then I need to discuss the changes with Klaus, which might be sometimes difficult ;)

On the other hand it is maybe not that useful to put the effort into this, because the CI-Module
needs to have the computing power to decode several streams. There is one module out,
which has enough power to decode two streams, but I don't know more.

And there is CI++ coming which is a pain in the as. The station force people to use this crap.
So at the end it might be a better solution to use the VDR CPU to decode the stream and then
you need to use dvbapi/oscam, which is not legal in a lot of countries.

I am not saying I don't do it, but currently the project is on hold.

BR
   Jasmin

**Comment by vdrtuxnet** [comment]
Hi Jasmin,

Thank you for the answer.
I absolutely agree with Klaus. ;)

Yes sure CI+ sucks, but ........ and X-mas is not very far ;-)

Then I will dig into that leaving VDR clean and maybe we will get a nice Christmas present.

Thx for your time and best regards

**Comment by jasmin-j** [comment]
MTD will be implemented by Klaus S. directly into the VDR. I expect this ready till end of March.
The ddci2 plugin will still serve as the interface to the DD CI hardware using the Kernel interface.

**Comment by emilsvennesson** [comment]
@jasmin-j I just thought I'd express my gratitude to you and Klaus for working on this! Thanks a lot -  it's very nice to finally have MTD support in Linux.

**Comment by jasmin-j** [comment]
You are welcome!
THX, Jasmin
